In [1]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd

In [2]:
jo_id = []
jo_tit = []
jo_sal = []
jo_sal_desc = []
jo_prov = []

In [3]:
count = 0

titles_list = ['Data-Analyst',
          'Data-Engineer',
          'Data-Scientist']

prov = ['Ontario',
        'Alberta',
        'British-Columbia',
        'Québec-Province',
        'Saskatchewan',
        'Yukon',
        'Nova-Scotia',
        'Manitoba',
        'New-Brunswick',
        'Newfoundland-And-Labrador',
        'Prince-Edward-Island',
        'Northwest-Territories',
        'Nunavut']

for idx,val in enumerate(titles_list):
    pages = True
    for province in prov:
        while pages == True:
            url = f"https://www.indeed.ca/salaries/{val}-Salaries,-{province}?start={count}"
            response = requests.get(url)
            soup = bs(response.text, 'lxml')

            if soup.find('table', class_='cmp-TitleSalary-table'):
                table = soup.find('table', class_='cmp-TitleSalary-table')
                titles = table.find_all('span', class_= None)
                salaries = table.find_all('span', class_= 'cmp-salary-amount')
                salary_desc = table.find_all('div', class_= 'cmp-sal-summary')
                
                jo_id.extend([idx + 1] * (len(titles)))
                jo_prov.extend([province] * (len(titles)))
                jo_tit.extend(title.text for title in titles)
                jo_sal.extend(float(salary.text[1:].replace(',','')) for salary in salaries)
                jo_sal_desc.extend(desc.text[-8:] for desc in salary_desc)
                
                if soup.find('span', class_='cmp-Pagination-link'):
                    count += 10
                    continue
                else:
                    break
            else:
                count = 0
                break

In [4]:
print(jo_prov)
print(len(jo_prov))

['Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Alberta', 'Alberta', 'Alberta', 'Alberta', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'Québec-Province', 'Québec-Province', 'Québec-Province', 'Québec-Province', 'Saskatchewan', 'Nova-Scotia', 'Nova-Scotia', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'Québec-Province', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Ontario', 'Alberta', 'Alberta', 'Alberta', 'Alberta', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'British-Columbia', 'Québec-Province', 'Québec-Province', 'Saskatchewan']
119

In [5]:
print(jo_tit)
print(len(jo_tit))

['York Region Data Analyst', 'York Region Data Analyst', 'Alliance Search Group Inc. Data Analyst', 'TekStaff IT Solutions Data Analyst', 'Infotek Direct Data Analyst', 'Veritaaq Data Analyst', 'Alliance Search Partners Inc. Data Analyst', 'Teamrecruiter Data Analyst', 'iVedha Inc. Data Analyst', 'Juventus Consulting Data Analyst', 'WELLINGTON-DUFFERIN-GUELPH PUBLIC HEALTH Data Analyst', 'Infotek Consulting Services Data Analyst', "St. Michael's Hospital Data Analyst", 'Brant County Health UNit Data Analyst', 'IFG - International Financial Group Data Analyst', 'Oxford County Data Analyst', 'County of Oxford Data Analyst', 'Lannick Group Data Analyst', 'Arrow Professional Services Data Analyst', 'altisHR Data Analyst', 'IPARTNER Data Analyst', 'Scotiabank Data Analyst', 'TransForm Shared Service Organization Data Analyst', 'A.O. Data Analyst', 'the Generator Data Analyst', 'International Financial Group Data Analyst', 'THE BAGG GROUP Data Analyst', 'Eastern Ontario Health Unit Data Analyst', 'University of Toronto Data Analyst', 'Onico Solutions Data Analyst', 'AppleOne Data Analyst', 'Options Consulting Solutions Data Analyst', 'TSE INC Data Analyst', 'The Pollack Group Data Analyst', 'The Executive Finance Group Inc. Data Analyst', 'Small Media Network Data Analyst', 'PATHWAY COMMUNICATIONS Data Analyst', 'Top Tier Bank Data Analyst', 'Sryas Inc. Data Analyst', 'Region of Waterloo Data Analyst', 'University of Waterloo Data Analyst', 'Government of Canada Data Analyst', 'ProVision Data Analyst', 'Apex Systems Data Analyst', 'Novitech Inc. Data Analyst', 'KIRCHHOFF Van-Rob Data Analyst', 'NEWAGE PRODUCTS Data Analyst', 'Robert Half Technology Data Analyst', 'Canada Clean Fuels Inc Data Analyst', '360 Net Solutions Data Analyst', 'London Health Sciences Centre Data Analyst', 'Malaka Management Services Data Analyst', 'ISG Search Data Analyst', 'Ministry of Health and Long-Term Care Data Analyst', 'Drake International Data Analyst', 'Prime Choice Data Analyst', 'IQ Partners Inc. Data Analyst', 'Government Of Alberta Data Analyst', 'City of Edmonton Data Analyst', 'University of Alberta Data Analyst', 'Strathcona County Data Analyst', 'City of Vancouver Data Analyst', 'Provincial Health Services Authority (PHSA) Data Analyst', 'Vancouver Coastal Health Data Analyst', 'University of British Columbia Data Analyst', 'BC Public Service Agency Data Analyst', 'Relic Entertainment Data Analyst', 'One Flat Fee Real Estate Inc Data Analyst', 'VERITAAQ TECHNOLOGY HOUSE INC. Data Analyst', 'Volt Data Analyst', 'SEGA Data Analyst', 'AutoHouse Technologies Inc. Data Analyst', 'Michael Page International Data Analyst', 'PRONEXIA Data Analyst', 'Gramma Partners Group Data Analyst', 'Axess Communications Data Analyst', 'University of Saskatchewan Data Analyst', 'Nova Scotia Health Authority Data Analyst', 'Dalhousie University Data Analyst', 'Shopify Data Engineer', 'Centre for Addiction and Mental Health Data Engineer', 'Shopify Inc. Data Engineer', 'Lannick Group Data Engineer', 'IsgSearch Data Engineer', 'Jobspring Partners Data Engineer', 'Workbridge Associates Data Engineer', 'TalentTank Recruiting Inc. Data Engineer', 'CyberCoders Data Engineer', 'Amazon.com Data Engineer', 'CyberCoders Data Engineer', 'SAPSOL Technologies Inc. Data Engineer', 'Jefferson Frank Data Engineer', 'Quartic.ai Data Scientist', 'Brainwerx Group Inc. Data Scientist', 'Staffinity Inc. Data Scientist', 'Shared Vision Management Search Data Scientist', 'ProVision Data Scientist', 'Michael Page International Data Scientist', 'Rang Technologies Inc. Data Scientist', 'CyberCoders Data Scientist', 'Jobspring Partners Data Scientist', 'Workbridge Associates Data Scientist', 'IPARTNER Data Scientist', "St. Michael's Hospital Data Scientist", 'HAZEL Data Scientist', 'Communications Security Establishment Data Scientist', 'Government Of Alberta Data Scientist', 'University of Alberta Data Scientist', 'University of Calgary Data Scientist', 'CyberCoders Data Scientist', 'University of British Columbia Data Scientist', 'CBRE Canada Limited Data Scientist', 'SAP Data Scientist', 'SEGA Data Scientist', 'Relic Entertainment Data Scientist', 'BC Public Service Agency Data Scientist', 'Ville de Montréal Data Scientist', 'upnup.io Data Scientist', 'Government of Saskatchewan Data Scientist']
119

In [6]:
print(jo_sal)
print(len(jo_sal))

[41.16, 40.18, 54.39, 48.5, 46.42, 48.32, 47.64, 39.66, 40.0, 37.0, 35.71, 32.64, 30.92, 30.59, 27.09, 26.06, 25.64, 25.38, 23.0, 20.37, 18.0, 51847.0, 56801.0, 16.0, 15.0, 28.33, 21.38, 57483.0, 67549.0, 63999.0, 58221.0, 60000.0, 80000.0, 40000.0, 75000.0, 3000.0, 57108.0, 75000.0, 78397.0, 60413.0, 57381.0, 82596.0, 75000.0, 77962.0, 42427.0, 47434.0, 57017.0, 53007.0, 32500.0, 63164.0, 28.32, 90000.0, 80000.0, 71168.0, 26.79, 14.97, 72115.0, 73533.0, 73067.0, 51271.0, 93872.0, 43.04, 33.56, 30.61, 51536.0, 58135.0, 89101.0, 29.0, 26.67, 14.73, 87180.0, 52780.0, 84853.0, 69296.0, 64809.0, 27.0, 71557.0, 31.47, 29.43, 149338.0, 42.13, 155477.0, 109301.0, 100000.0, 132165.0, 118266.0, 115726.0, 97904.0, 95791.0, 173241.0, 69.0, 119.0, 82508.0, 117211.0, 103210.0, 102046.0, 101871.0, 89450.0, 80000.0, 145001.0, 118740.0, 118160.0, 50000.0, 40.22, 500.0, 741.0, 83657.0, 67878.0, 49221.0, 106691.0, 54067.0, 159688.0, 96489.0, 90803.0, 90803.0, 66820.0, 106191.0, 62000.0, 7424.0]
119

In [7]:
print(jo_sal_desc)
print(len(jo_sal_desc))

['per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per hour', 'per year', 'per year', 'per hour', 'per hour', 'per hour', 'per hour', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'er month', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per hour', 'per year', 'per year', 'per year', 'per hour', 'per hour', 'per year', 'per year', 'per year', 'per year', 'per year', 'per hour', 'per hour', 'per hour', 'per year', 'per year', 'per year', 'per hour', 'per hour', 'per hour', 'per year', 'per year', 'per year', 'per year', 'per year', 'per hour', 'per year', 'per hour', 'per hour', 'per year', 'per hour', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per hour', 'per hour', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per hour', 'per week', 'per week', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'per year', 'er month']
119

In [8]:
df = pd.DataFrame(data={'ID':jo_id,
                        'Title': jo_tit,
                        'Province': jo_prov,
                        'Annual_salary': jo_sal,
                        'typ':jo_sal_desc})

df

,ID,Title,Province,Annual_salary,typ
0,1,York Region Data Analyst,Ontario,41.16,per hour
1,1,York Region Data Analyst,Ontario,40.18,per hour
2,1,Alliance Search Group Inc. Data Analyst,Ontario,54.39,per hour
3,1,TekStaff IT Solutions Data Analyst,Ontario,48.50,per hour
4,1,Infotek Direct Data Analyst,Ontario,46.42,per hour
5,1,Veritaaq Data Analyst,Ontario,48.32,per hour
6,1,Alliance Search Partners Inc. Data Analyst,Ontario,47.64,per hour
7,1,Teamrecruiter Data Analyst,Ontario,39.66,per hour
8,1,iVedha Inc. Data Analyst,Ontario,40.00,per hour
9,1,Juventus Consulting Data Analyst,Ontario,37.00,per hour
10,1,WELLINGTON-DUFFERIN-GUELPH PUBLIC HEALTH Data ...,Ontario,35.71,per hour
11,1,Infotek Consulting Services Data Analyst,Ontario,32.64,per hour
12,1,St. Michael's Hospital Data Analyst,Ontario,30.92,per hour
13,1,Brant County Health UNit Data Analyst,Ontario,30.59,per hour
14,1,IFG - International Financial Group Data Analyst,Ontario,27.09,per hour
15,1,Oxford County Data Analyst,Ontario,26.06,per hour
16,1,County of Oxford Data Analyst,Ontario,25.64,per hour
17,1,Lannick Group Data Analyst,Ontario,25.38,per hour
18,1,Arrow Professional Services Data Analyst,Ontario,23.00,per hour
19,1,altisHR Data Analyst,Ontario,20.37,per hour
20,1,IPARTNER Data Analyst,Ontario,18.00,per hour
21,1,Scotiabank Data Analyst,Ontario,51847.00,per year
22,1,TransForm Shared Service Organization Data Ana...,Ontario,56801.00,per year
23,1,A.O. Data Analyst,Ontario,16.00,per hour
24,1,the Generator Data Analyst,Ontario,15.00,per hour
25,1,International Financial Group Data Analyst,Ontario,28.33,per hour
26,1,THE BAGG GROUP Data Analyst,Ontario,21.38,per hour
27,1,Eastern Ontario Health Unit Data Analyst,Ontario,57483.00,per year
28,1,University of Toronto Data Analyst,Ontario,67549.00,per year
29,1,Onico Solutions Data Analyst,Ontario,63999.00,per year
...,...,...,...,...,...
89,2,CyberCoders Data Engineer,British-Columbia,173241.00,per year
90,2,SAPSOL Technologies Inc. Data Engineer,British-Columbia,69.00,per hour
91,2,Jefferson Frank Data Engineer,Québec-Province,119.00,per hour
92,3,Quartic.ai Data Scientist,Ontario,82508.00,per year
93,3,Brainwerx Group Inc. Data Scientist,Ontario,117211.00,per year
94,3,Staffinity Inc. Data Scientist,Ontario,103210.00,per year
95,3,Shared Vision Management Search Data Scientist,Ontario,102046.00,per year
96,3,ProVision Data Scientist,Ontario,101871.00,per year
97,3,Michael Page International Data Scientist,Ontario,89450.00,per year
98,3,Rang Technologies Inc. Data Scientist,Ontario,80000.00,per year
99,3,CyberCoders Data Scientist,Ontario,145001.00,per year
100,3,Jobspring Partners Data Scientist,Ontario,118740.00,per year
101,3,Workbridge Associates Data Scientist,Ontario,118160.00,per year
102,3,IPARTNER Data Scientist,Ontario,50000.00,per year
103,3,St. Michael's Hospital Data Scientist,Ontario,40.22,per hour
104,3,HAZEL Data Scientist,Ontario,500.00,per week
105,3,Communications Security Establishment Data Sci...,Ontario,741.00,per week
106,3,Government Of Alberta Data Scientist,Alberta,83657.00,per year
107,3,University of Alberta Data Scientist,Alberta,67878.00,per year
108,3,University of Calgary Data Scientist,Alberta,49221.00,per year
109,3,CyberCoders Data Scientist,Alberta,106691.00,per year
110,3,University of British Columbia Data Scientist,British-Columbia,54067.00,per year
111,3,CBRE Canada Limited Data Scientist,British-Columbia,159688.00,per year
112,3,SAP Data Scientist,British-Columbia,96489.00,per year
113,3,SEGA Data Scientist,British-Columbia,90803.00,per year
114,3,Relic Entertainment Data Scientist,British-Columbia,90803.00,per year
115,3,BC Public Service Agency Data Scientist,British-Columbia,66820.00,per year
116,3,Ville de Montréal Data Scientist,Québec-Province,106191.00,per year
117,3,upnup.io Data Scientist,Québec-Province,62000.00,per year
118,3,Government of Saskatchewan Data Scientist,Saskatchewan,7424.00,er month

In [9]:
df['Annual_salary'].loc[df['typ'].str.contains('month')] = df['Annual_salary'] * 12
df['Annual_salary'].loc[df['typ'].str.contains('week')] = df['Annual_salary'] * 52
df['Annual_salary'].loc[df['typ'].str.contains('hour')] = df['Annual_salary'] * 2080
df

C:\Users\Llobo\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

,ID,Title,Province,Annual_salary,typ
0,1,York Region Data Analyst,Ontario,85612.8,per hour
1,1,York Region Data Analyst,Ontario,83574.4,per hour
2,1,Alliance Search Group Inc. Data Analyst,Ontario,113131.2,per hour
3,1,TekStaff IT Solutions Data Analyst,Ontario,100880.0,per hour
4,1,Infotek Direct Data Analyst,Ontario,96553.6,per hour
5,1,Veritaaq Data Analyst,Ontario,100505.6,per hour
6,1,Alliance Search Partners Inc. Data Analyst,Ontario,99091.2,per hour
7,1,Teamrecruiter Data Analyst,Ontario,82492.8,per hour
8,1,iVedha Inc. Data Analyst,Ontario,83200.0,per hour
9,1,Juventus Consulting Data Analyst,Ontario,76960.0,per hour
10,1,WELLINGTON-DUFFERIN-GUELPH PUBLIC HEALTH Data ...,Ontario,74276.8,per hour
11,1,Infotek Consulting Services Data Analyst,Ontario,67891.2,per hour
12,1,St. Michael's Hospital Data Analyst,Ontario,64313.6,per hour
13,1,Brant County Health UNit Data Analyst,Ontario,63627.2,per hour
14,1,IFG - International Financial Group Data Analyst,Ontario,56347.2,per hour
15,1,Oxford County Data Analyst,Ontario,54204.8,per hour
16,1,County of Oxford Data Analyst,Ontario,53331.2,per hour
17,1,Lannick Group Data Analyst,Ontario,52790.4,per hour
18,1,Arrow Professional Services Data Analyst,Ontario,47840.0,per hour
19,1,altisHR Data Analyst,Ontario,42369.6,per hour
20,1,IPARTNER Data Analyst,Ontario,37440.0,per hour
21,1,Scotiabank Data Analyst,Ontario,51847.0,per year
22,1,TransForm Shared Service Organization Data Ana...,Ontario,56801.0,per year
23,1,A.O. Data Analyst,Ontario,33280.0,per hour
24,1,the Generator Data Analyst,Ontario,31200.0,per hour
25,1,International Financial Group Data Analyst,Ontario,58926.4,per hour
26,1,THE BAGG GROUP Data Analyst,Ontario,44470.4,per hour
27,1,Eastern Ontario Health Unit Data Analyst,Ontario,57483.0,per year
28,1,University of Toronto Data Analyst,Ontario,67549.0,per year
29,1,Onico Solutions Data Analyst,Ontario,63999.0,per year
...,...,...,...,...,...
89,2,CyberCoders Data Engineer,British-Columbia,173241.0,per year
90,2,SAPSOL Technologies Inc. Data Engineer,British-Columbia,143520.0,per hour
91,2,Jefferson Frank Data Engineer,Québec-Province,247520.0,per hour
92,3,Quartic.ai Data Scientist,Ontario,82508.0,per year
93,3,Brainwerx Group Inc. Data Scientist,Ontario,117211.0,per year
94,3,Staffinity Inc. Data Scientist,Ontario,103210.0,per year
95,3,Shared Vision Management Search Data Scientist,Ontario,102046.0,per year
96,3,ProVision Data Scientist,Ontario,101871.0,per year
97,3,Michael Page International Data Scientist,Ontario,89450.0,per year
98,3,Rang Technologies Inc. Data Scientist,Ontario,80000.0,per year
99,3,CyberCoders Data Scientist,Ontario,145001.0,per year
100,3,Jobspring Partners Data Scientist,Ontario,118740.0,per year
101,3,Workbridge Associates Data Scientist,Ontario,118160.0,per year
102,3,IPARTNER Data Scientist,Ontario,50000.0,per year
103,3,St. Michael's Hospital Data Scientist,Ontario,83657.6,per hour
104,3,HAZEL Data Scientist,Ontario,26000.0,per week
105,3,Communications Security Establishment Data Sci...,Ontario,38532.0,per week
106,3,Government Of Alberta Data Scientist,Alberta,83657.0,per year
107,3,University of Alberta Data Scientist,Alberta,67878.0,per year
108,3,University of Calgary Data Scientist,Alberta,49221.0,per year
109,3,CyberCoders Data Scientist,Alberta,106691.0,per year
110,3,University of British Columbia Data Scientist,British-Columbia,54067.0,per year
111,3,CBRE Canada Limited Data Scientist,British-Columbia,159688.0,per year
112,3,SAP Data Scientist,British-Columbia,96489.0,per year
113,3,SEGA Data Scientist,British-Columbia,90803.0,per year
114,3,Relic Entertainment Data Scientist,British-Columbia,90803.0,per year
115,3,BC Public Service Agency Data Scientist,British-Columbia,66820.0,per year
116,3,Ville de Montréal Data Scientist,Québec-Province,106191.0,per year
117,3,upnup.io Data Scientist,Québec-Province,62000.0,per year
118,3,Government of Saskatchewan Data Scientist,Saskatchewan,89088.0,er month

In [12]:
df_fin = df.drop(['typ'], axis = 1)

df_fin.to_csv(r'../1_Extracted_Inputs/Salary_extracted_input.csv', index = False)